### ISSUE TITLE
problem with output format csv

### ISSUE THREAD

**Issue by michabbb** [crate/crash#91] opened 2015-11-25 20:09 UTC
hi there,

it looks to me there is a problem with the ouput format csv.
a select at the crate web console gives me this output:

![schnappschuss_112515_090313_pm](https://cloud.githubusercontent.com/assets/3524595/11408202/f206ec6a-93b7-11e5-806b-266659e19726.jpg)

the same query piped to crash gives me this:

`cat /tmp/query |/usr/share/crate/bin/crash --format=csv `

![schnappschuss_112515_090515_pm](https://cloud.githubusercontent.com/assets/3524595/11408254/3a8df942-93b8-11e5-8109-22b38d1d2378.jpg)

`/usr/share/crate/bin/crash --version` --> `0.14.2`

don´t know where the `u` is coming from.

the `false` is coming from a object field with a very complex and deep structure, like this:

`attributes['xxxxxx']['list']['de']`

crash has been installed via crate debian package manager.
hope these infos help.

**Comment by chaudum** [comment] 2015-11-26 06:36
Hi @michabbb 
The `u` prefix is coming from Python meaning that it is a Unicode string. It seems like for the `csv` output the string representation is used, not the actual string values. This is a bug we have to address.
We'll let you know when it is fixed.

**Comment by michabbb** [comment] 2015-11-26 13:12
THX !

**Comment by celaus** [comment] 2015-11-27 12:42
Hi @michabbb, we just merged the bugfix :+1: #93

**Comment by michabbb** [comment] 2015-11-27 13:25
thx.. how long or when does a bugfix like this goes into the debian package ?

**Comment by celaus** [comment] 2015-12-01 09:42
Hi, sorry for being a bit late: We have updated the pypi package: https://pypi.python.org/pypi/crash/ and as soon as we do a new Crate release, the new Shell will also be included.

Cheers, Claus

**Comment by michabbb** [comment] 2015-12-01 10:59
i removed crate (because i am running it with docker) and tried to install crash stand-alone:

```
pip install crash
Downloading/unpacking crash
  Downloading crash-0.14.3.tar.gz
  Running setup.py egg_info for package crash
    
    warning: no previously-included files matching 'tests.py' found under directory 'src'
Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib/python2.7/dist-packages (from crash)
Downloading/unpacking colorama (from crash)
  Downloading colorama-0.3.3.tar.gz
  Running setup.py egg_info for package colorama
    
Downloading/unpacking Pygments (from crash)
  Downloading Pygments-2.0.2.tar.gz (3.5Mb): 3.5Mb downloaded
  Running setup.py egg_info for package Pygments
    
Downloading/unpacking crate>=0.11.2 (from crash)
  Downloading crate-0.13.6.tar.gz (55Kb): 55Kb downloaded
  Running setup.py egg_info for package crate
    
    warning: no files found matching '*.rst' under directory 'src'
    warning: no previously-included files matching 'tests*.py' found under directory 'src'
Downloading/unpacking appdirs>=1.2,<2.0 (from crash)
  Downloading appdirs-1.4.0.tar.gz
  Running setup.py egg_info for package appdirs
    
Downloading/unpacking prompt-toolkit==0.52 (from crash)
  Downloading prompt_toolkit-0.52.tar.gz (152Kb): 152Kb downloaded
  Running setup.py egg_info for package prompt-toolkit
    
    no previously-included directories found matching 'examples/sample?/build'
Downloading/unpacking urllib3 (from crate>=0.11.2->crash)
  Downloading urllib3-1.12.tar.gz (151Kb): 151Kb downloaded
  Running setup.py egg_info for package urllib3
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from crate>=0.11.2->crash)
Downloading/unpacking wcwidth (from prompt-toolkit==0.52->crash)
  Downloading wcwidth-0.1.5.tar.gz
  Running setup.py egg_info for package wcwidth
    
Installing collected packages: crash, colorama, Pygments, crate, appdirs, prompt-toolkit, urllib3, wcwidth
  Running setup.py install for crash
    Skipping installation of /usr/local/lib/python2.7/dist-packages/crate/__init__.py (namespace package)
    
    warning: no previously-included files matching 'tests.py' found under directory 'src'
    Installing /usr/local/lib/python2.7/dist-packages/crash-0.14.3-nspkg.pth
    Installing crash script to /usr/local/bin
  Running setup.py install for colorama
    
  Running setup.py install for Pygments
    
    Installing pygmentize script to /usr/local/bin
  Running setup.py install for crate
    Skipping installation of /usr/local/lib/python2.7/dist-packages/crate/__init__.py (namespace package)
    
    warning: no files found matching '*.rst' under directory 'src'
    warning: no previously-included files matching 'tests*.py' found under directory 'src'
    Installing /usr/local/lib/python2.7/dist-packages/crate-0.13.6-nspkg.pth
  Running setup.py install for appdirs
    
  Running setup.py install for prompt-toolkit
    
    no previously-included directories found matching 'examples/sample?/build'
  Running setup.py install for urllib3
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
  Running setup.py install for wcwidth
    
Successfully installed crash colorama Pygments crate appdirs prompt-toolkit urllib3 wcwidth
Cleaning up...
```

but calling crash gives me this error:

```
/usr/local/bin/crash
Traceback (most recent call last):
  File "/usr/local/bin/crash", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six>=1.9.0
```
HELP !? 

and btw...  `https://cdn.crate.io/downloads/releases/crash_standalone_latest` 
has not been updatet, the current version is: `0.14.2`

**Comment by chaudum** [comment] 2015-12-01 11:28
@michabbb what `pip` version do you have installed?
could you run

```console
$ pip --version
$ pip list | grep six
```
and post the output?

after quickly looking around, this problem could be caused by an outdated `distribute` version. try to run:
```console
$ pip install --upgrade distribute
```

Also: `crash_standalone_latest` is now `0.14.3`

**Comment by michabbb** [comment] 2015-12-01 11:41
**system**
`debian 7`

**pip --version**
`pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)`

**pip list|grep six**
the command *list* is unknown in my version, so i tried `pip freeze`
```
GnuPGInterface==0.3.2
Pygments==2.0.2
SOAPpy==0.12.0
appdirs==1.4.0
argparse==1.2.1
backports.ssl-match-hostname==3.4.0.2
chardet==2.0.1
colorama==0.3.3
crash==0.14.3
crate==0.13.6
distribute==0.7.3
docker-py==0.6.0
fpconst==0.7.2
nagiosplugin==1.2.2
prompt-toolkit==0.52
pycurl==7.19.0
python-apt==0.8.8.2
python-debian==0.1.21
python-debianbts==1.11
reportbug==6.4.4
requests==2.5.0
six==1.8.0
unattended-upgrades==0.1
urllib3==1.12
wcwidth==0.1.5
websocket-client==0.22.0
wsgiref==0.1.2
```

**Comment by michabbb** [comment] 2015-12-01 11:42
is there a chance to force six 1.9 ??

**Comment by chaudum** [comment] 2015-12-01 12:31
@michabbb 
```console
$ pip install six==1.9.0
```

**Comment by michabbb** [comment] 2015-12-01 12:36
perfect, worked: 

```
crash --version
0.14.3
```

thanks!!

**Closed** 2015-12-01 12:38 UTC

**Comment by michabbb** [comment] 2015-12-01 12:40
sorry, something has changed with the headline of the csv format and i don´t know if this happend by accident:

**version 0.14.2** 

`attributes['xxxxxx']['list']['de']`

**version 0.14.3** 

`attributes[\'xxxxxx\'][\'list\'][\'de\']`

now the keys inside the object are quoted ;( 
so **again** i have to use `sed` to remove them from output. i don´t see any reason to quote here....

**Comment by chaudum** [comment] 2015-12-01 14:42
@michabbb this is actually a limitation of csv, see http://crate.readthedocs.org/projects/crash/en/0.14.3/formats.html#csv

what you should do is using a column alias:

```sql
select attributes['xxxxxx']['list']['de'] as attr_list_de from foo;
```

**Comment by michabbb** [comment] 2015-12-01 15:48
okay, thanks
