### ISSUE TITLE
Download Crash bundle parse error

### ISSUE THREAD

**Issue by yuchen99** [crate/crash#82] opened 2015-09-21 03:58 UTC
```
[/opt/crate/bin]./crash_standalone_latest 
./crash_standalone_latest/crate/client/http.py:315: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
cr> 
cr> 
cr> 
cr> \connect 127.0.0.1:4200;
./crash_standalone_latest/crate/crash/command.py:457: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
Failed to parse: 127.0.0.1:4200;
cr> \connect 127.0.0.1:4200;
Failed to parse: 127.0.0.1:4200;
```
uname -a 
```
Linux dbproxy 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```
python -V
Python 2.6.6

**Comment by seut** [comment] 2015-09-21 07:32
The problem is, that a semicolon `;` is not wanted (and seems to lead to parsing errors) for all internal (non-sql) crash commands. 
This will work:
```cr> \connect 127.0.0.1:4200```

Anyway we'll put a task on our backlog to just ignore the last semicolon in such a case.
Or maybe you want to contribute? ;)

**Comment by mfussenegger** [comment] 2015-10-08 21:48
Closing this as it has been fixed with https://github.com/crate/crash/commit/d6386ebed0abdd036d768ed6c47c476470bf4cde

The fix will be part of the next crash release.

**Closed by mfussenegger** 2015-10-08 21:48 UTC
